# Generated by Django 5.0.14 on 2026-09-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_perfilprofessor_telefone'),
        ('professores', '0002_alter_disponibilidade_dia_semana'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together={('professor', 'disciplina', 'dia_semana', 'horario_inicio')},
        ),
    ]
