# Generated by Django 5.0.14 on 2026-09-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, choices=[('cancelado_aluno', 'Cancelado pelo aluno'), ('cancelado_professor', 'Cancelado pelo professor'), ('no_show', 'Não comparecimento (no-show)')], max_length=30),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='percentual_reembolso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='reembolsado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status_reembolso',
            field=models.CharField(choices=[('nao_aplicavel', 'Não aplicável'), ('solicitado', 'Solicitado'), ('sem_direito', 'Sem direito a reembolso')], default='nao_aplicavel', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_reembolsado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='DenunciaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_mensagem_snapshot', models.TextField()),
                ('motivo', models.CharField(choices=[('ofensa_assedio', 'Ofensa/Assédio'), ('ameaca', 'Ameaça'), ('conteudo_sexual', 'Conteúdo sexual impróprio'), ('discriminacao', 'Discriminação'), ('contato_externo', 'Tentativa de contato fora da plataforma'), ('outro', 'Outro')], max_length=30)),
                ('detalhes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_mensagens', to='agendamento.agendamento')),
                ('denunciado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('denunciante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='agendamento.mensagem')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
