# Generated by Django 5.0.14 on 2026-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'PIX'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], default='PIX', max_length=20),
        ),
    ]
