# Generated by Django 5.0.14 on 2026-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_pagamento_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='duracao_minutos',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (150, '2h30')], default=60),
        ),
    ]
