# Generated by Django 5.0.14 on 2026-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_agendamento_duracao_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='chat_lido_aluno_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='chat_lido_professor_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
