# Generated by Django 5.0.14 on 2026-09-11 00:28

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofessor',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to=contas.models.caminho_curriculo),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='motivo_rejeicao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='status_verificacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='verificacao_detalhe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
