# Generated by Django 5.0.14 on 2026-09-24 12:51

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_aprovar_professores_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofessor',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=contas.models.caminho_avatar),
        ),
    ]
