# Generated by Django 5.0.14 on 2026-09-24 14:37

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_perfilprofessor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=contas.models.caminho_avatar),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='sobre',
            field=models.TextField(blank=True),
        ),
    ]
