# Generated by Django 5.0.14 on 2026-09-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_perfilaluno_avatar_perfilaluno_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='materias_interesse',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('graduacao', 'Graduação'), ('pos_graduacao', 'Pós-graduação'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('reforco_escolar', 'Reforço escolar'), ('vestibular_enem', 'Vestibular / ENEM'), ('concurso_publico', 'Concurso público'), ('idioma', 'Aprender um idioma'), ('curso_superior', 'Apoio em disciplina da faculdade'), ('desenvolvimento_profissional', 'Desenvolvimento profissional'), ('hobby_interesse_pessoal', 'Hobby / interesse pessoal'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CartaoSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('validade', models.CharField(max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='contas.perfilaluno')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='contas.perfilaluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='contas.perfilprofessor')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('aluno', 'professor')},
            },
        ),
    ]
