# Generated by Django 5.0.14 on 2026-09-24 18:14

import contas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_perfilaluno_materias_interesse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofessor',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='documento_identidade',
            field=models.FileField(blank=True, null=True, upload_to=contas.models.caminho_documento_identidade),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='metodologia_ensino',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='politica_cancelamento_horas',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='politica_cancelamento_percentual_tardio',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='status_documento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='video_apresentacao',
            field=models.FileField(blank=True, null=True, upload_to=contas.models.caminho_video_apresentacao),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='video_apresentacao_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('chave_pix_usada', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saques', to='contas.perfilprofessor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
