# Generated by Django 5.0.14 on 2026-09-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_perfilprofessor_chave_pix_perfilprofessor_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprofessor',
            name='politica_cancelamento_horas',
        ),
        migrations.RemoveField(
            model_name='perfilprofessor',
            name='politica_cancelamento_percentual_tardio',
        ),
    ]
