# Generated by Django 5.0.14 on 2026-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_remove_perfilprofessor_politica_cancelamento_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofessor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
